package com.example.kotoba

object Alam {
    fun getKotoba(): ArrayList<N4> {
        ArrayList<N4>().also {
            it.apply {
                add(
                    N4(
                        "Batang",
                        "えだ",
                        "Eda"
                    )
                )
                add(
                    N4(
                        "Daun",
                        "は",
                        "Ha"
                    )
                )
                add(
                    N4(
                        "Hutan",
                        "はやし",
                        "Hayashi"
                    )
                )
                add(
                    N4(
                        "Api",
                        "ひ",
                        "Hi"
                    )
                )
                add(
                    N4(
                        "Matahari/Hari",
                        "ひ",
                        "Hi"
                    )
                )
                add(
                    N4(
                        "Cahaya",
                        "ひかり",
                        "Hikari"
                    )
                )
                add(
                    N4(
                        "Bintang",
                        "ほし",
                        "Hoshi"
                    )
                )
                add(
                    N4(
                        "Batu",
                        "いし",
                        "Ishi"
                    )
                )
                add(
                    N4(
                        "Pemandangan",
                        "けしき",
                        "Keshiki"
                    )
                )
                add(
                    N4(
                        "Musim",
                        "きせつ",
                        "Kisetsu"
                    )
                )
                add(
                    N4(
                        "Awan",
                        "くも",
                        "Kumo"
                    )
                )
                add(
                    N4(
                        "Rumput",
                        "くさ",
                        "Kusa"
                    )
                )
                add(
                    N4(
                        "Udara",
                        "くうき",
                        "Kuuki"
                    )
                )
                add(
                    N4(
                        "Danau",
                        "みずうみ",
                        "Mizuumi"
                    )
                )
                add(
                    N4(
                        "Danau",
                        "みずうみ",
                        "Mizuumi"
                    )
                )
                add(
                    N4(
                        "Rimba",
                        "もり",
                        "Mori"
                    )
                )
                add(
                    N4(
                        "Lereng, Tanjakan",
                        "さか",
                        "Saka"
                    )
                )
                add(
                    N4(
                        "Dunia",
                        "せかい",
                        "Sekai"
                    )
                )
                add(
                    N4(
                        "Pulau",
                        "しま",
                        "Shima"
                    )
                )
                add(
                    N4(
                        "Pasir",
                        "すな",
                        "Suna"
                    )
                )
                add(
                    N4(
                        "Cuaca",
                        "てんき",
                        "Tenki"
                    )
                )
                add(
                    N4(
                        "Bulan",
                        "",
                        "Tenki"
                    )
                )
}