package com.example.kotoba

object KataKerjaPart1 {
    fun getKotoba(): ArrayList<N4> {
        ArrayList<N4>().also {
            it.apply {
                add(
                    N4(
                        "Naik, Mendaki",
                        "あがる",
                        "Agaru"
                    )
                )
                add(
                    N4(
                        "Memberi",
                        "あげる",
                        "Ageru"
                    )
                )
                add(
                    N4(
                        "Memberi salam",
                        "あいさつする",
                        "Aisatsusuru"
                    )
                )
                add(
                    N4(
                        "Kosong, Lowong",
                        "あく",
                        "Aku"
                    )
                )
                add(
                    N4(
                        "Kosong, Lowong",
                        "あく",
                        "Aku"
                    )
                )
                add(
                    N4(
                        "Memandu, Memberi informasi",
                        "あんないする",
                        "Annaisuru"
                    )
                )
                add(
                    N4(
                        "Berkumpul",
                        "あつまる",
                        "Atsumaru"
                    )
                )
                add(
                    N4(
                        "Mengumpulkan",
                        "あつめる",
                        "Atsumeru"
                    )
                )
                add(
                    N4(
                        "Bertemu, Menemui",
                        "あう",
                        "Au"
                    )
                )
                add(
                    N4(
                        "Meminta maaf",
                        "あやまる",
                        "Ayamaru"
                    )
                )
                add(
                    N4(
                        "Terkejut, Kaget",
                        "びっくりする",
                        "Bikkurisuru"
                    )
                )
                add(
                    N4(
                        "Memeriksa",
                        "チェックスル",
                        "Chekkusuru"
                    )
                )
                add(
                    N4(
                        "Berhati-hati",
                        "ちゅういする",
                        "Chuuisuru"
                    )
                )
                add(
                    N4(
                        "Menyuntikan",
                        "ちゅうしゃする",
                        "Chuushasuru"
                    )
                )
                add(
                    N4(
                        "Sungkan",
                        "えんりょする",
                        "Enryosuru"
                    )
                )
                add(
                    N4(
                        "Memilih",
                        "えらぶ",
                        "Erabu"
                    )
                )
                add(
                    N4(
                        "Bertambah, Meningkat",
                        "ふえる",
                        "Fueru"
                    )
                )
                add(
                    N4(
                        "Menginjak",
                        "ふむ",
                        "Fumu"
                    )
                )
                add(
                    N4(
                        "Mulai turun (hujan atau salju)",
                        "ふりだす",
                        "Furidasu"
                    )
                )
                add(
                    N4(
                        "Menjadi gemuk",
                        "ふとる",
                        "Futoru"
                    )
                )
                add(
                    N4(
                        "Memulai",
                        "はじめる",
                        "Hajimeru"
                    )
                )
                add(
                    N4(
                        "Mengangkut, Membawa",
                        "はこぶ",
                        "Hajimeru"
                    )
                )
                add(
                    N4(
                        "Bertentangan, Berlawanan, Terbalik",
                        "はんたいする",
                        "Hantaisuru"
                    )
                )
                add(
                    N4(
                        "Membayar",
                        "はらう",
                        "Harau"
                    )
                )
                add(
                    N4(
                        "Menjawab, Menyahut",
                        "へんじする",
                        "Henjisuru"
                    )
                )
                add(
                    N4(
                        "Menjadi dingin",
                        "ひえる",
                        "Hieru"
                    )
                )
                add(
                    N4(
                        "Bersinar, Berkilau",
                        "ひかる",
                        "Hikaru"
                    )
                )
                add(
                    N4(
                        "Menarik keluar",
                        "ひきだす",
                        "Hikidasu"
                    )
                )
                add(
                    N4(
                        "Pindah(rumah)",
                        "ひっこす",
                        "Hikkosu"
                    )
                )
                add(
                    N4(
                        "Buka",
                        "ひらく",
                        "Hiraku"
                    )
                )
                add(
                    N4(
                        "Memungut",
                        "ひろう",
                        "Hirou"
                    )
                )
                add(
                    N4(
                        "Memuji",
                        "ほめる",
                        "Hameru"
                    )
                )
                add(
                    N4(
                        "Menerjemahkan",
                        "ほんやくする",
                        "Hon'yakusuru"
                    )
                )
                add(
                    N4(
                        "Menyiarkan, Menayangkan",
                        "ほうそうする",
                        "Housousuru"
                    )
                )
                add(
                    N4(
                        "Menganiaya, Memperlakukan buruk",
                        "いじめる",
                        "Ijimeru"
                    )
                )
                add(
                    N4(
                        "Hidup",
                        "いきる",
                        "Ikiru"
                    )
                )
                add(
                    N4(
                        "Tergesa-gesa",
                        "いそぐ",
                        "Isogu"
                    )
                )
                add(
                    N4(
                        "Mempersiapkan",
                        "じゅんびする",
                        "Junbisuru"
                    )
                )
                add(
                    N4(
                        "Merubah",
                        "かえる",
                        "Kaeru"
                    )
                )
                add(
                    N4(
                        "Menggantungkan, Memasang",
                        "かける",
                        "Kakeru"
                    )
                )
                add(
                    N4(
                        "Peduli",
                        "かまう",
                        "Kamau"
                    )
                )
                add(
                    N4(
                        "Menggigit, Mengunyah",
                        "かむ",
                        "Kamu"
                    )
                )
                add(
                    N4(
                        "Berpikir",
                        "かんがえる",
                        "Kangaeru"
                    )
                )
                add(
                    N4(
                        "Merapikan, Membereskan",
                        "かたずける",
                        "Katazukeru"
                    )
                )
                add(
                    N4(
                        "Menang",
                        "かつ",
                        "Katsu"
                    )
                )
                add(
                    N4(
                        "Kering",
                        "かわく",
                        "Kawaku"
                    )
                )
                add(
                    N4(
                        "Berubah, Berbeda",
                        "かわる",
                        "Kawaru"
                    )
                )
                add(
                    N4(
                        "Pulang - pergi, sering berkunjung",
                        "かよう",
                        "Kayou"
                    )
                )
                add(
                    N4(
                        "Menghias, Mendekor",
                        "かざる",
                        "Kazaru"
                    )
                )
                add(
                    N4(
                        "Bertengkar, Berkelahi",
                        "けんかする",
                        "Kenkasuru"
                    )
                )
                add(
                    N4(
                        "Terdengar",
                        "きこえる",
                        "Kikoeru"
                    )
                )
                add(
                    N4(
                        "Tetap, Pasti",
                        "きまる",
                        "Kimaru"
                    )
                )
                add(
                    N4(
                        "Memustuskan, Menentukan",
                        "きめる",
                        "Kimeru"
                    )
                )
                add(
                    N4(
                        "Padat, Meresap",
                        "こむ",
                        "Komu"
                    )
                )
                add(
                    N4(
                        "Rusak",
                        "こしょうする",
                        "Koshousuru"
                    )
                )
                add(
                    N4(
                        "Menjawab",
                        "こたえる",
                        "Kotaeru"
                    )
                )
                add(
                    N4(
                        "Rusak",
                        "こわれる",
                        "Kowareru"
                    )
                )
                add(
                    N4(
                        "Merusak",
                        "こわす",
                        "Kowasu"
                    )
                )
                add(
                    N4(
                        "Membandingkan",
                        "",
                        "Kowasu"
                    )
                )
}