package com.example.kotoba

object KataKerjaPart3 {
    fun getKotoba(): ArrayList<N4> {
        ArrayList<N4>().also {
            it.apply {
                add(
                    N4(
                        "Memeriksa",
                        "しらべる",
                        "Shiraberu"
                    )
                )
                add(
                    N4(
                        "Memberitahu, Mengabarkan",
                        "しらせる",
                        "Shiraseru"
                    )
                )
                add(
                    N4(
                        "Mempersiapkan",
                        "したくする",
                        "Shitakusuru"
                    )
                )
                add(
                    N4(
                        "Mengerti, Menyetujui",
                        "しょうちする",
                        "Shouchisuru"
                    )
                )
                add(
                    N4(
                        "Memperkenalkan",
                        "しょうかいする",
                        "Shoukaisuru"
                    )
                )
                add(
                    N4(
                        "Mengundang",
                        "しょうたいする",
                        "Shoutaisuru"
                    )
                )
                add(
                    N4(
                        "Berangkat",
                        "しゅぱっつする",
                        "Shuppatsusuru"
                    )
                )
                add(
                    N4(
                        "Hadir",
                        "しゅっせきする",
                        "Shussekisuru"
                    )
                )
                add(
                    N4(
                        "Merawat, Memelihara",
                        "そだてる",
                        "Sodateru"
                    )
                )
                add(
                    N4(
                        "Lulus, Tamat",
                        "そつぎょうする",
                        "Sotsugyousuru"
                    )
                )
                add(
                    N4(
                        "Berdiskusi",
                        "そうだんする",
                        "Soudansuru"
                    )
                )
                add(
                    N4(
                        "Tergelincir, Terpeleset",
                        "すべる",
                        "Suberu"
                    )
                )
                add(
                    N4(
                        "Melampaui, Melewati",
                        "すぎる",
                        "Sugiru"
                    )
                )
                add(
                    N4(
                        "Melampaui, Melewati",
                        "すぎる",
                        "Sugiru"
                    )
                )
                add(
                    N4(
                        "Kosong, Lapar",
                        "すく",
                        "Suku"
                    )
                )
                add(
                    N4(
                        "Menyelesaikan, Menghabiskan",
                        "すむ",
                        "Sumu"
                    )
                )
                add(
                    N4(
                        "Maju",
                        "すすむ",
                        "Susumu"
                    )
                )
                add(
                    N4(
                        "Membuang",
                        "すてる",
                        "Suteru"
                    )
                )
                add(
                    N4(
                        "Keluar dari rumah sakit",
                        "たい'いんする",
                        "Tai'insuru"
                    )
                )
                add(
                    N4(
                        "Menikmati",
                        "たのしむ",
                        "Tanoshimu"
                    )
                )
                add(
                    N4(
                        "Jatuh, Roboh",
                        "たおれる",
                        "Taoreru"
                    )
                )
                add(
                    N4(
                        "Cukup",
                        "たりる",
                        "Tariru"
                    )
                )
                add(
                    N4(
                        "Menambah, Memperbanyak",
                        "たす",
                        "Tasu"
                    )
                )
                add(
                    N4(
                        "Membangun, Mendirikan",
                        "たてる",
                        "Tateru"
                    )
                )
                add(
                    N4(
                        "Berdiri",
                        "たてる",
                        "Tateru"
                    )
                )
                add(
                    N4(
                        "Mencari, Bertanya",
                        "たずねる",
                        "Tazuneru"
                    )
                )
                add(
                    N4(
                        "Berkunjung",
                        "たずねる",
                        "Tazuneru"
                    )
                )
                add(
                    N4(
                        "Membantu",
                        "てつだう",
                        "Tetsudau"
                    )
                )
                add(
                    N4(
                        "Membantu",
                        "てつだう",
                        "Tetsudau"
                    )
                )
                add(
                    N4(
                        "Mengirim, Menyampaikan, Melaporkan",
                        "とどける",
                        "Todokeru"
                    )
                )
                add(
                    N4(
                        "Menginap, Bermalam",
                        "とまる",
                        "Tomaru"
                    )
                )
                add(
                    N4(
                        "Memberhentikan, Menahan",
                        "とめる",
                        "Tomeru"
                    )
                )
                add(
                    N4(
                        "Melalui, Melewati",
                        "とおる",
                        "Tooru"
                    )
                )
                add(
                    N4(
                        "Menukar, Mengganti",
                        "とりかえる",
                        "Torikaeru"
                    )
                )
                add(
                    N4(
                        "Menangkap",
                        "つかまえる",
                        "Tsukamaeru"
                    )
                )
                add(
                    N4(
                        "Merendam",
                        "つける",
                        "Tsukeru"
                    )
                )
                add(
                    N4(
                        "Melekat, Menempel",
                        "つく",
                        "Tsuku"
                    )
                )
                add(
                    N4(
                        "Melekat, Menempel",
                        "つく",
                        "Tsuku"
                    )
                )
                add(
                    N4(
                        "Mengajak",
                        "つれる",
                        "Tsureru"
                    )
                )
                add(
                    N4(
                        "Memancing",
                        "つる",
                        "Tsuru"
                    )
                )
                add(
                    N4(
                        "Menyampaikan",
                        "つたえる",
                        "Tsutaeru"
                    )
                )
                add(
                    N4(
                        "Membungkus",
                        "つつむ",
                        "Tsutsumu"
                    )
                )
                add(
                    N4(
                        "Meneruskan, Melanjutkan",
                        "つずける",
                        "Tsuzukeru"
                    )
                )
                add(
                    N4(
                        "Berlanjut, Bersambung",
                        "つずく",
                        "Tsuzuku"
                    )
                )
                add(
                    N4(
                        "Menanam",
                        "うえる",
                        "Ueru"
                    )
                )
                add(
                    N4(
                        "Bergerak",
                        "うごく",
                        "Ugoku"
                    )
                )
                add(
                    N4(
                        "Menerima, Mendapat",
                        "うける",
                        "Ukeru"
                    )
                )
                add(
                    N4(
                        "Berolahraga",
                        "うんどうする",
                        "Undousuru"
                    )
                )
                add(
                    N4(
                        "Mengemudi, Menyetir",
                        "うんてんする",
                        "Untensuru"
                    )
                )
                add(
                    N4(
                        "Memukul",
                        "うつ",
                        "Utsu"
                    )
                )
                add(
                    N4(
                        "Pindah, Menular",
                        "うつる",
                        "Utsuru"
                    )
                )
                add(
                    N4(
                        "Menyalin, Mengkopi, Memotret",
                        "うつす",
                        "Utsusu"
                    )
                )
                add(
                    N4(
                        "Berpisah, Bercerai",
                        "わかれる",
                        "Wakareru"
                    )
                )
                add(
                    N4(
                        "Mendidihkan",
                        "わかす",
                        "Wakasu"
                    )
                )
                add(
                    N4(
                        "Mendidih",
                        "わく",
                        "Waku"
                    )
                )
                add(
                    N4(
                        "Tertawa",
                        "わらう",
                        "Warau"
                    )
                )
                add(
                    N4(
                        "Pecah, Terbelah",
                        "われる",
                        "Wareru"
                    )
                )
                add(
                    N4(
                        "Terbakar, Terpanggang",
                        "やける",
                        "Yakeru"
                    )
                )
                add(
                    N4(
                        "Berguna",
                        "やくにたつ",
                        "Yakunitatsu"
                    )
                )
                add(
                    N4(
                        "Membakar, Memanggang",
                        "やく",
                        "Yaku"
                    )
                )
                add(
                    N4(
                        "Berjanji",
                        "やくそくする",
                        "Yakusokusuru"
                    )
                )
                add(
                    N4(
                        "Berhenti, Memberhentikan",
                        "やめる",
                        "Yameru"
                    )
                )
                add(
                    N4(
                        "Menjadi kurus",
                        "やせる",
                        "Yaseru"
                    )
                )
                add(
                    N4(
                        "Menjadi kotor",
                        "よごれる",
                        "Yogoreru"
                    )
                )
                add(
                    N4(
                        "Senang, Gembira",
                        "よろこぶ",
                        "Yorokobu"
                    )
                )
                add(
                    N4(
                        "Mampir, Singgah",
                        "よる",
                        "Yoru"
                    )
                )
                add(
                    N4(
                        "Mempersiapkan pelajaran",
                        "よしゅうする",
                        "Yoshuusuru"
                    )
                )
                add(
                    N4(
                        "Merencanakan",
                        "よていする",
                        "Yoteisuru"
                    )
                )
                add(
                    N4(
                        "Mempersiapkan",
                        "よういする",
                        "Youisuru"
                    )
                )
                add(
                    N4(
                        "Memesan",
                        "よやくする",
                        "Yoyakusuru"
                    )
                )
                add(
                    N4(
                        "Mengimpor",
                        "ゆにゅうする",
                        "Yunyuusuru"
                    )
                )
                add(
                    N4(
                        "Goyang, Mengayun",
                        "ゆれる",
                        "Yureru"
                    )
                )
                add(
                    N4(
                        "Mengekspor",
                        "ゆしゅつする",
                        "Yushutsusuru"
                    )
                )
            }
            return it
        }
    }
}